### ISSUE TITLE
project that is the server part link is broken

### ISSUE THREAD

**Issue by moh1122** [villacak/TicTacToeWeb#1]
Hello i like your project but how can i download the project that is the server part. So the users can play against each other.
Thank you

**Comment by villacak** [comment]
Hi there,

I am developing now the app with SWIFT, though the server part can be used
for any client, mean Android and PCs.
The server part is called TicTacToeServer, and you can find it here
https://github.com/villacak/TicTacToeServer, for download it you can
download it using git client, doing a checkout, branch the project or click
the download zip button

On Thu, Feb 25, 2016 at 9:51 AM, moh1122 notifications@github.com wrote:

> Hello i like your project but how can i download the project that is the
> server part. So the users can play against each other.
> Thank you
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/villacak/TicTacToeWeb/issues/1.

## 

Regards

Klaus Villaca

**Comment by villacak** [comment]
Into _info.plist_ -> _Application Transport Security Settings_ -> _Exception Domains_, replace localhost for you server URL, also update the _Constants.swift_ -> _URL_BASE_ to have the same URL. 
I think that has a way to have the URL just in one place, the right place would be into the plist file.
